- id: no-commit-on-branch
  name: No commit on master or main
  description: Do no allow any commit on either specified branch.
  entry: bin/no-commit-on-branch.sh
  language: script
  always_run: true

- id: bump-r-package-version
  name: Bump r package version
  description: Bump date and version in file Description.
  entry: Rscript bin/bump-r-package-version.R
  language: r
  always_run: true

- id: lintr
  name: lintr
  description: check if a .R file is lint free (using lintr)
  entry: Rscript bin/lintr.R
  language: r
  files: '(\.[rR]profile|\.R|\.Rmd|\.Rnw|\.r|\.rmd|\.rnw)$'
  exclude: 'renv/activate\.R'
  minimum_pre_commit_version: "2.13.0"
