- id: no-commit-on-branch
  name: No commit on master or main
  description: Do no allow any commit on either specified branch.
  entry: bin/no-commit-on-branch.sh
  language: script
  always_run: true

- id: bump-r-package-version
  name: Bump r package version
  description: Bump date and version in file Description.
  entry: Rscript bin/bump-r-package-version.sh
  language: r
  always_run: true
